### ISSUE TITLE
Convex Local Backend Errors

### ISSUE THREAD

**Issue by MCPE10** [a16z-infra/ai-town#243]
<img width="566" alt="Screenshot 2024-06-05 at 07 59 48" src="https://github.com/a16z-infra/ai-town/assets/88267863/022a2ae6-555b-4683-ac01-41f21a1d92fd">
I am getting these errors when launching the backend, and in the AI Town, I can't click around to move my character.
Does anyone know what is going on? See my previous issue #240 too. Thanks!

**Comment by ianmacartney** [comment]
This happens when there's a lot of contention reading & writing to a certain document. You can check out the document it's referencing - my guess is there is some contention updating the `lastViewed` timestamp - when a bunch of clients all try to tell the world it's not stale, and all try to do it at once. we could add some jitter there, but hopefully these are all happening from `heartbeatWorld` which doesn't matter too much if it fails. bummer it doesn't say locally what function it's in in the log. If it's causing issues / isn't in heartbeatWorld plz re-open!
